### ISSUE TITLE
The response of nic.scan() is changed.

### ISSUE THREAD

**Issue by TakuroFukamizu** [sipeed/MaixPy_scripts#10]
[network/demo_wifi_ap_scan.py](https://github.com/sipeed/MaixPy_scripts/blob/master/network/demo_wifi_ap_scan.py) is not working at maixpy firmware v0.3.2.

please see below the comment.
https://github.com/sipeed/MaixPy_scripts/issues/8#issuecomment-513581272

**Comment by Neutree** [comment]
http://dl.sipeed.com/MAIX/MaixPy/release/master/maixpy_v0.4.0_6_g715665c/

**Comment by TakuroFukamizu** [comment]
This issue is fixed at above firmware. 

![image](https://user-images.githubusercontent.com/1331349/61672629-4a191b80-ad27-11e9-93ad-3c094f7c20c4.png)

network/demo_wifi_ap_scan.py is working now.
Thank you @Neutree !
