### ISSUE TITLE
kpu.forward OS Error

### ISSUE THREAD

**Issue by Narduzzi** [sipeed/MaixPy_scripts#11]
Hello,

I'm trying to run the following code : 

```
import sensor
import image
import lcd
import KPU as kpu

lcd.init()
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.run(1)
task = kpu.load(0x300000) # you face model in flash at address 0x300000
print("Done")
img = sensor.snapshot()

a = kpu.forward(task, img,1)  #<--- this is the problematic line

print("OK")
```

However, MaixPy IDE return the message "OS ERROR". 
What could be the problem? How can I solve it?

Thank you for your help!

**Comment by minyatos** [comment]
> a = kpu.forward(task, img)  #<--- this is the problematic line

**Comment by Neutree** [comment]
upgrade firmware and try again https://dl.sipeed.com/MAIX/MaixPy/release/master
