### ISSUE TITLE
Maix Dock 支援 Uart or Serial通訊嗎?

### ISSUE THREAD

**Issue by matrisys** [sipeed/MaixPy_scripts#113]
您好,
請問Maix Dock 支援 Uart or Serial 通訊嗎?
下列的PIN若當作Uart Port使用有定義此PIN的Samaple code?
IO6(WIFI_TX_MCU_RX)
IO7(WIFI_TX_MCU_TX)
謝謝!

**Comment by Neutree** [comment]
https://github.com/sipeed/MaixPy_scripts/blob/master/hardware/demo_uart_many.py

https://github.com/sipeed/MaixPy_scripts/blob/master/hardware/demo_uart_loop.py

https://github.com/sipeed/MaixPy_scripts/blob/master/network/network_espat.py

**Comment by hungtsosung** [comment]
謝謝, 已測試完成, 可使用Wifi_TX, RX 的Pin腳當作Uart Port 使用.
