### ISSUE TITLE
Sipeed Maixpy Amigo and Cube, on board mic don't work

### ISSUE THREAD

**Issue by YvesLafont** [sipeed/MaixPy_scripts#118]
Hi,
i'am unable to get the internal microphone working on Amigo and Cube.
Have someone a working MaixPy source to check the internal mic ?
I tried several exemples, checking the correct I2S mapping pins, but no result.
Compiling, is ok, without runtime errors, but no result
I use the last 6.2 firmware (normal, not minimum)
Thank you very much for help.

Yves

**Comment by YvesLafont** [comment]
Update :  Internal microphone work well when uploading "es8374.py" and care with i2c and i2s pins. The FFT demo work
But that work not for the Cube .. The error is "pins 33, 34 and 35 are used by unknown" (I2S Cube pins for receiver)
What is the correct definition for the Cube ?

**Comment by junhuanchen** [comment]
https://wiki.sipeed.com/soft/maixpy/en/course/media/audio.html
