### ISSUE TITLE
can't show fmap

### ISSUE THREAD

**Issue by changwenkai101** [sipeed/MaixPy_scripts#12]
The demo in 2 at https://maixpy.sipeed.com/zh/libs/Maix/kpu.html, that shows the feature map doesn't work. 

The error "kpu: can't convet float fmap yet" occurs, no matter how to modify the index and num. The last layer of the network is anti-quantized, however, as far as I understand, the other layers are quantized, and their feature maps should be displayed, but they are not.

How do I modify this demo to make it work？

**Comment by chahatdeep** [comment]
Did you resolve this issue?
