### ISSUE TITLE
No module named cpufreq

### ISSUE THREAD

**Issue by Maximellerbach** [sipeed/MaixPy_scripts#23]
hey, I noticed when I tried to change/check the cpu/kpu frequency that the cpufreq module doesn't seems to be working, I installed the maixpy_v0.3.2_full version, I don't think I have made anything wrong. Hope this problem will be fixed soon !

`import cpufreq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'cpufreq'`

**Comment by Neutree** [comment]
upgrage firmware  http://dl.sipeed.com/MAIX/MaixPy/release/master/

**Comment by Maximellerbach** [comment]
even with the latest  v0.4.0-101-g553fdfd it doesn't work !
![image](https://user-images.githubusercontent.com/38923282/69913804-27b5ae00-143d-11ea-9f6f-4a7ef2a5faa9.png)

**Comment by Maximellerbach** [comment]
or with v0.5.0
![image](https://user-images.githubusercontent.com/38923282/69913963-b119b000-143e-11ea-90ae-857aec0ef259.png)

**Comment by Neutree** [comment]
https://maixpy.sipeed.com/zh/libs/Maix/freq.html

**Comment by Maximellerbach** [comment]
thanks a lot !

**Comment by Maximellerbach** [comment]
when tring to change kpu frequency (set function is working fine with cpu frequency):
![image](https://user-images.githubusercontent.com/38923282/69974949-8dca3000-1526-11ea-951c-26942277486a.png)

**Comment by Maximellerbach** [comment]
nevermind, I found where the problem was !
Thank you again !
