### ISSUE TITLE
GPIO and pins

### ISSUE THREAD

**Issue by manns** [sipeed/MaixPy_scripts#32]
While trying to setup a MaixDuino with the GroveShield V2, I am usuccessfully trying to access IO pins, i.e. a button and an LED.
I would expect the LED example code to light the Grove LED on D7, and the button code to yield if the button on D3 is pressed. Both is not the case.

```Python
>>> fm.register(board_info.LED_R,fm.fpioa.GPIOHS0,force=True)
1
>>> led_r = GPIO(GPIO.GPIOHS0, GPIO.OUT)
>>> led_r.value()
0
>>> led_r.value(1)
>>> led_r.value()
0
```
How can I access the digital pins with MaixPy?

**Comment by junhuanchen** [comment]
It's fixed
