### ISSUE TITLE
ImportError: no module named 'touchscreen'

### ISSUE THREAD

**Issue by enrique-torres** [sipeed/MaixPy_scripts#34]
Hi, there seems to be an issue with the touchscreen demo. I'm using the Maixpy IDE and it says that it can't find the touchscreen module.

**Comment by enrique-torres** [comment]
It also says that board_info isn't callable. I'm using MaixPy 5.0.0

**Comment by Createyouraccount-alt** [comment]
same for me: ImportError: no module named 'touchscreen' 
No help yet?

**Comment by enrique-torres** [comment]
Sorry I didn't close my own issue. I later used the lvgl binary and it worked for me @Createyouraccount-alt

**Comment by f123f998** [comment]
Hello, how did you solve this problem?
