### ISSUE TITLE
Is it possible that Miax Dock can make itself Access Point or Wifi Hotspot ?

### ISSUE THREAD

**Issue by izzabellerina** [sipeed/MaixPy_scripts#35]
Hello everyone. when I've seen many the document of MiaxPy, I could not find source code that about Access Point  or Wifi Hotspot . Many of them are connect the wifi hotspot but doesn't make MaixPy itself Wifi hotspot. Does anyone help me about making access point please? 
Thank you in advance.

**Comment by Neutree** [comment]
https://github.com/sipeed/MaixPy_scripts/blob/master/network/demo_wifi_ap_scan.py

```
nic.enable_ap(SSID, PASSWD)
```
