### ISSUE TITLE
NameError: name 'fm' isn't defined

### ISSUE THREAD

**Issue by wolfbomb** [sipeed/MaixPy_scripts#43]
trying to run this code 

> from Maix import GPIO
> fm.register(board_info.LED_B, fm.fpioa.GPIO0)
> led_r=GPIO(GPIO.GPIO0,GPIO.OUT)
> led_r.value(0)

But it am getting this error. Any help will be highly appreciated. Thanks in advance. I am using MaixGo.

> Traceback (most recent call last):
>   File "<stdin>", line 2, in <module>
> NameError: name 'fm' isn't defined
> MicroPython v0.5.0-38-g4c4d5b6 on 2020-04-10; Sipeed_M1 with kendryte-k210

**Comment by Neutree** [comment]
from fpioa_manager import fm
