### ISSUE TITLE
Maixduino demo_send_pic  OSError: [WinError 10049] Invalid address requested in your context

### ISSUE THREAD

**Issue by nicolaivalenti** [sipeed/MaixPy_scripts#51]
When trying to use this send pic demo with the pic_server.py (the code that I need to run on the PC side to get the image, you can find it here: tools_on_PC/network/pic_server.py) I get the following error on the CMD:
![thes](https://user-images.githubusercontent.com/56894506/83816798-88ab9080-a6c3-11ea-8ae1-366c7a395e88.PNG)
 
Please help me, I have no idea of what to do next

**Comment by Neutree** [comment]
https://stackoverflow.com/questions/46042476/oserror-winerror-10049-how-do-i-tackle-this-error

**Comment by Neutree** [comment]
replace the IP with your IP
