### ISSUE TITLE
How to add Speech Reconizer demo to Maixpy??

### ISSUE THREAD

**Issue by Agostin42** [sipeed/MaixPy_scripts#56]
Hi, I'm a beginner with sipeed maix boards, and I don't know how to add the demo Speech Reconizer in the Maixpy ​​IDE, can someone help me?

**Comment by huoxingwen** [comment]
I have the same trouble

**Comment by shintarof** [comment]
When you build the firmware, you can use it by selecting Enable Speech recognizer in the Modules configurations section

**Comment by GuilhermeAgostin** [comment]
Olha, atualmente estou usando como exemplo esse codigo:  https://github.com/sipeed/MaixPy_scripts/blob/master/multimedia/speech_recognizer/speech_recognizer.py

Minha Versao de IDE do Maixpy é a 0.2.5 

![Captura de Tela (286)](https://user-images.githubusercontent.com/59300376/85911472-d5cede00-b7fb-11ea-85f6-cca1b1b8a3d3.png)


E como arquivo bin 

![Captura de Tela (287)](https://user-images.githubusercontent.com/59300376/85911635-a40a4700-b7fc-11ea-893c-2009296942ec.png)

Infelizmente ainda nao entendi o que fazer @shintarof

**Comment by shintarof** [comment]
Please refer to the following instructions on how to build the firmware

https://github.com/sipeed/MaixPy/blob/ master/build.md

**Comment by lancewj** [comment]
你好我想问下，你的运行成功了，我运行之后提示以下错误。
![1](https://user-images.githubusercontent.com/30410304/87615740-faa4da00-c745-11ea-84d1-42a8420648b4.png)
![2](https://user-images.githubusercontent.com/30410304/87615750-fed0f780-c745-11ea-88f6-c2c458638bf2.png)
我把提示报错的相关部分注释后提示后，能够记录语音，但是不能识别。
请问有遇到过这种情况吗

**Comment by shanejohnpaul** [comment]
I tried to run this demo. Right now there is no module named SpeechRecognizer.

**Comment by Neutree** [comment]
@QinYUN575

**Comment by junhuanchen** [comment]
https://github.com/sipeed/MaixPy_scripts/tree/master/multimedia/speech_recognizer

**Comment by junhuanchen** [comment]
https://github.com/sipeed/MaixPy_scripts/blob/master/multimedia/speech_recognizer/isolated_word.py
https://github.com/sipeed/MaixPy_scripts/blob/master/multimedia/speech_recognizer/test_maix_asr.py
in maixpy_0.5.1_128 +
