### ISSUE TITLE
res = img.find_qrcodes()

### ISSUE THREAD

**Issue by MarceloVMG** [sipeed/MaixPy_scripts#57]
Hi, I'm beginning with the MaixPy, and i'm trying to use the script to read QR Codes, but not work, and show the error "res = img.find_qrcodes()"

![Capture](https://user-images.githubusercontent.com/66638434/85881198-9f6d7080-b7b3-11ea-9817-460651ca35f3.PNG)

**Comment by Neutree** [comment]
you should burn full function firmware

![image](https://user-images.githubusercontent.com/8625829/89748780-903e4a00-daf7-11ea-9603-23bab0957942.png)
