### ISSUE TITLE
receiving image from an HTTPS url, ESP32

### ISSUE THREAD

**Issue by ChahidTALHA** [sipeed/MaixPy_scripts#67]
Hi everyone,
I am using Maixduino Board (Firmware: **maixpy_v0.5.0_98_g7ec09ea**) with its ESP32 (**ESP32_SPI firmware version: 1.4.0** ) to implement a project,
I referred to the code in the link : 
https://github.com/sipeed/MaixPy_scripts/blob/master/network/demo_esp32_socket.py
in order to download an image from **http url** and worked fine.
Now I am asking if there is any example and methods to download images from **https url** for the ESP32.
Let me know if you need more information.
Thanks in advance.

**Comment by ChahidTALHA** [comment]
can i have an answer about this question?

**Comment by Neutree** [comment]
try the latest  firmware, it support https now

**Comment by ChahidTALHA** [comment]
Thanks for your answer,
i will check it and get back to you with a feedback.

**Comment by junhuanchen** [comment]
see this https://github.com/sipeed/MaixPy_scripts/blob/master/network/demo_https_get.py
