### ISSUE TITLE
issue with esp32

### ISSUE THREAD

**Issue by leozlee** [sipeed/MaixPy_scripts#7]
When i want to run demo esp32_read adc.
I meet a problem with "AttributeError:'module'object has no attribute 'ESP32_SPI'.
I use maixpy_v0.3.2_full.bin

**Comment by Neutree** [comment]
v0.3.2 not support, master branch do

**Comment by leozlee** [comment]
Thanks for reply.
So, how am I supposed to deal with this problem?

**Comment by leozlee** [comment]
ok,I know.
I use the newer firmware from http://dl.sipeed.com/MAIX/MaixPy/release/master/
This problem fix

**Comment by leozlee** [comment]
Thanks again
