### ISSUE TITLE
请问怎么实现base64转image的过程?

### ISSUE THREAD

**Issue by jaxkingdom** [sipeed/MaixPy_scripts#71]

**Comment by Neutree** [comment]
将 jpeg图片的base64转成bytes: http://docs.micropython.org/en/latest/library/ubinascii.html?highlight=base64#ubinascii.a2b_base64 

然后`image.Image(jpeg, from_bytes=True)`

**Comment by jaxkingdom** [comment]
> 将 jpeg图片的base64转成bytes: http://docs.micropython.org/en/latest/library/ubinascii.html?highlight=base64#ubinascii.a2b_base64
> 
> 然后`image.Image(jpeg, from_bytes=True)`

谢谢，不过您可能没有明白我的用意，我是想通过串口将电脑上的图片实时传输给k210，在k210上进行识别，这样可以实现嘛？

再次感谢！

**Comment by Neutree** [comment]
可, 串口把jpeg传过来,然后用我上面的方法构造img就好了
