### ISSUE TITLE
Speech recognition example not working on MAIX DOCK

### ISSUE THREAD

**Issue by dootamroy** [sipeed/MaixPy_scripts#75]
microphone not taking input.

**Comment by dootamroy** [comment]
can you please help!
still haven't got any resolution!!

**Comment by junhuanchen** [comment]
mark

**Comment by junhuanchen** [comment]
https://github.com/sipeed/MaixPy_scripts/blob/master/multimedia/speech_recognizer/demo_isolated_word_on_maixdock.py
