### ISSUE TITLE
Use 64 GB SD with ExFat

### ISSUE THREAD

**Issue by deby13** [sipeed/MaixPy_scripts#78]
The documentation recommend the use of  a fast SD and it says it only accepts FAT not FAT32 or NTFS and up to 128 GB was tested.  Nevertheless the FAT fits only 4GB, so at least it shout accept FAT32 or ExFAT, I tried to force format 64GB with FAT but it does not accept, so how should I proceed? I am using a SDXC 64GB V30

**Comment by Neutree** [comment]
Just use FAT32 with MBR partition, no NTFS or EXFAT support, 4GiB limit just for single file, not for whole partition size

**Comment by Neutree** [comment]
if you remain have some problems, create issue in MaixPy repository

**Comment by deby13** [comment]
Thank you very much.
