### ISSUE TITLE
为什么不能使用两个socket？

### ISSUE THREAD

**Issue by nieaowei** [sipeed/MaixPy_scripts#82]
我尝试同时使用mqtt和http进行网络通信，发现只有一个可以正常运行。当我单独使用mqtt时，只能订阅或者发布，而不能同时发布订阅。

**Comment by junhuanchen** [comment]
现在MaixPy底层还不能创建两个 socket 实例，主要原因是协议缓冲区没有两份，数据没有解析流入到不同的 socket 对象中。

想要解决这个问题，可以在一个 socket 上做调整，例如 http 都是发生在同一个 socket 上的，mqtt 可以绕过底层实现，直接对目标网卡做操作请求。

退其次可以用完交换，或走其他串口向 AT / SPI 网卡请求数据
