### ISSUE TITLE
TypeError: unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by TakuroFukamizu** [sipeed/MaixPy_scripts#9]
I've tried to run /network/demo_wifi_ap_scan.py but I got the following error.

![image](https://user-images.githubusercontent.com/1331349/61595728-e4993200-ac35-11e9-924a-4f4f82bd8503.png)

That error happens at this line 
https://github.com/sipeed/MaixPy_scripts/blob/6928fe172a77402915850a27c6f8fe04a75b8223/network/demo_wifi_ap_scan.py#L7

I've used the latest firmware v0.3.2 and Maix Dan Doc board.

What is wrong?

**Comment by Neutree** [comment]
http://dl.sipeed.com/MAIX/MaixPy/release/master/maixpy_v0.4.0_6_g715665c/

**Comment by TakuroFukamizu** [comment]
It's fixed at above firmware. Thank you @Neutree !
