### ISSUE TITLE
ImportError SpeechRecognizer

### ISSUE THREAD

**Issue by deby13** [sipeed/MaixPy_scripts#95]
I am trying many examples for Maixduino and all of them does not work but this I would like see it working which is the Speech recognition, it show the following error, ImportError cannot import name SpeechRecognizer, I've been searching all around and could not find this module, How can I fix this, please advise

**Comment by deby13** [comment]
just adding an info, I have tried with MAix bit and MAixduino

**Comment by myuunosuke** [comment]
"SpeechRecognizer" has been changed to "speech_recognizer".

Please see this thread.
https://github.com/sipeed/MaixPy/issues/368

Try "help('modules')" command and make sure your firmware is built with speech_recognizer module.
If not, you will need to build your own firmware with "speech_recognizer" enabled.

I've tested  "isolated_word.py" with my Maixduino with firmware v0.6.2 with speech_recognizer enabled, and it worked.

**Comment by deby13** [comment]
Thank you
